<?php

namespace firesnake\entities\proxies\__CG__\firesnake\isItRunning\entities;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Check extends \firesnake\isItRunning\entities\Check implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'firesnake\\isItRunning\\entities\\Check' . "\0" . 'id', '' . "\0" . 'firesnake\\isItRunning\\entities\\Check' . "\0" . 'name', '' . "\0" . 'firesnake\\isItRunning\\entities\\Check' . "\0" . 'url', '' . "\0" . 'firesnake\\isItRunning\\entities\\Check' . "\0" . 'checker', '' . "\0" . 'firesnake\\isItRunning\\entities\\Check' . "\0" . 'runnerConfig', '' . "\0" . 'firesnake\\isItRunning\\entities\\Check' . "\0" . 'useHeaders', '' . "\0" . 'firesnake\\isItRunning\\entities\\Check' . "\0" . 'environments', '' . "\0" . 'firesnake\\isItRunning\\entities\\Check' . "\0" . 'owner'];
        }

        return ['__isInitialized__', '' . "\0" . 'firesnake\\isItRunning\\entities\\Check' . "\0" . 'id', '' . "\0" . 'firesnake\\isItRunning\\entities\\Check' . "\0" . 'name', '' . "\0" . 'firesnake\\isItRunning\\entities\\Check' . "\0" . 'url', '' . "\0" . 'firesnake\\isItRunning\\entities\\Check' . "\0" . 'checker', '' . "\0" . 'firesnake\\isItRunning\\entities\\Check' . "\0" . 'runnerConfig', '' . "\0" . 'firesnake\\isItRunning\\entities\\Check' . "\0" . 'useHeaders', '' . "\0" . 'firesnake\\isItRunning\\entities\\Check' . "\0" . 'environments', '' . "\0" . 'firesnake\\isItRunning\\entities\\Check' . "\0" . 'owner'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Check $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function addEnvironment(\firesnake\isItRunning\entities\CheckableEnvironment $environment): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEnvironment', [$environment]);

        parent::addEnvironment($environment);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEnvironment(\firesnake\isItRunning\entities\CheckableEnvironment $environment): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEnvironment', [$environment]);

        parent::removeEnvironment($environment);
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): string
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', []);

        return parent::getUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrl(string $url): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrl', [$url]);

        parent::setUrl($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getChecker(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChecker', []);

        return parent::getChecker();
    }

    /**
     * {@inheritDoc}
     */
    public function setChecker(string $checker): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChecker', [$checker]);

        parent::setChecker($checker);
    }

    /**
     * {@inheritDoc}
     */
    public function getRunnerConfig(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRunnerConfig', []);

        return parent::getRunnerConfig();
    }

    /**
     * {@inheritDoc}
     */
    public function setRunnerConfig(string $runnerConfig): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRunnerConfig', [$runnerConfig]);

        parent::setRunnerConfig($runnerConfig);
    }

    /**
     * {@inheritDoc}
     */
    public function isUseHeaders(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isUseHeaders', []);

        return parent::isUseHeaders();
    }

    /**
     * {@inheritDoc}
     */
    public function setUseHeaders(bool $useHeaders): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUseHeaders', [$useHeaders]);

        parent::setUseHeaders($useHeaders);
    }

    /**
     * {@inheritDoc}
     */
    public function hasEnvironment(\firesnake\isItRunning\entities\CheckableEnvironment $environment): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasEnvironment', [$environment]);

        return parent::hasEnvironment($environment);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlParams(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlParams', []);

        return parent::getUrlParams();
    }

    /**
     * {@inheritDoc}
     */
    public function getOwner(): \firesnake\isItRunning\entities\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwner', []);

        return parent::getOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwner(\firesnake\isItRunning\entities\User $owner): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwner', [$owner]);

        parent::setOwner($owner);
    }

}
