<?php

namespace firesnake\isItRunning\http;

class Twig404Response extends TwigResponse
{
    public function send(): void
    {
        http_response_code(404);
        parent::send(); // TODO: Change the autogenerated stub
    }
}